### ISSUE TITLE
"Connection reset" errors with `artifact-caching-proxy.privatelink.azurecr.io`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#4241]
### Service(s)

Artifact-caching-proxy

### Summary

In https://github.com/jenkinsci/bom/pull/3190 (and other BOM jobs I have run with the `full-test` label) three tests failed:

- https://ci.jenkins.io/job/Tools/job/bom/job/PR-3190/56/pipeline-console/?selected-node=942
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-3190/56/pipeline-console/?selected-node=1059
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-3190/56/pipeline-console/?selected-node=1535

In all three cases, this message was printed to the console shortly before the failure:

```
INFO: using artifact caching proxy server 'http://artifact-caching-proxy.privatelink.azurecr.io:8080/'.
```

These failures were not reproducible locally. In my experience re-running these tests often doesn't help as it just results in a different set of tests failing. ACP doesn't seem reliable enough to complete a `full-test` run, or at least it wasn't on Monday and today when I tried.

I captured some of the logs that show a "Connection reset" message from the abovementioned server `artifact-caching-proxy.privatelink.azurecr.io`:

```
[…]
[2024-08-14T16:57:27.839Z] 2024-08-14 16:57:27.809+0000 [id=1]	INFO	o.j.t.t.m.ExternalMavenRunner#run: Running mvn -B -V -e -ntp -pl :pipeline-graph-analysis -Dmaven.test.failure.ignore=true -Dsurefire.rerunFailingTestsCount=1 -DforkCount=.75C -Dsurefire.excludesFile=/home/jenkins/agent/workspace/Tools_bom_PR-3190/excludes.txt -DoverrideWar=/home/jenkins/agent/workspace/Tools_bom_PR-3190/target/megawar-weekly.war -Djenkins.version=2.472 -DuseUpperBounds=true hpi:resolve-test-dependencies hpi:test-hpl hpi:test-runtime surefire:test -Djenkins-test-harness.version=2244.v77428109fd1f -DupperBoundsExcludes=org.junit.jupiter:junit-jupiter-api in /home/jenkins/agent/workspace/Tools_bom_PR-3190/target/pct-work/pipeline-graph-analysis-plugin >> /home/jenkins/agent/workspace/Tools_bom_PR-3190/target/pct-work/logs/pipeline-graph-analysis/v216.vfd8b_ece330ca__against_core_version_2.472.log
[…]
[2024-08-14T16:57:41.806Z] [ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.51:resolve-test-dependencies (default-cli) on project pipeline-graph-analysis: Unable to resolve dependencies: Could not resolve dependencies for project org.jenkins-ci.plugins:pipeline-graph-analysis:hpi:999999-SNAPSHOT
[2024-08-14T16:57:41.806Z] [ERROR] dependency: org.bouncycastle:bcprov-jdk18on:jar:1.78.1 (compile)
[2024-08-14T16:57:41.806Z] [ERROR] 	Could not transfer artifact org.bouncycastle:bcprov-jdk18on:jar:1.78.1 from/to azure-internal (http://artifact-caching-proxy.privatelink.azurecr.io:8080/): Connection reset
[2024-08-14T16:57:41.806Z] [ERROR] -> [Help 1]
[2024-08-14T16:57:41.806Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.51:resolve-test-dependencies (default-cli) on project pipeline-graph-analysis: Unable to resolve dependencies
[2024-08-14T16:57:41.806Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:333)
[2024-08-14T16:57:41.806Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
[2024-08-14T16:57:41.807Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
[2024-08-14T16:57:41.808Z]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
[2024-08-14T16:57:41.808Z]     at java.lang.reflect.Method.invoke (Method.java:580)
[2024-08-14T16:57:41.808Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
[2024-08-14T16:57:41.808Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
[2024-08-14T16:57:41.808Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
[2024-08-14T16:57:41.808Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[2024-08-14T16:57:41.808Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to resolve dependencies
[2024-08-14T16:57:41.808Z]     at org.jenkinsci.maven.plugins.hpi.TestDependencyMojo.resolveDependencies (TestDependencyMojo.java:790)
[2024-08-14T16:57:41.808Z]     at org.jenkinsci.maven.plugins.hpi.TestDependencyMojo.execute (TestDependencyMojo.java:245)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
[2024-08-14T16:57:41.808Z]     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
[2024-08-14T16:57:41.809Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
[2024-08-14T16:57:41.809Z]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
[2024-08-14T16:57:41.809Z]     at java.lang.reflect.Method.invoke (Method.java:580)
[2024-08-14T16:57:41.809Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
[2024-08-14T16:57:41.809Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
[2024-08-14T16:57:41.809Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
[2024-08-14T16:57:41.809Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[2024-08-14T16:57:41.810Z] Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.jenkins-ci.plugins:pipeline-graph-analysis:hpi:999999-SNAPSHOT
[2024-08-14T16:57:41.810Z] dependency: org.bouncycastle:bcprov-jdk18on:jar:1.78.1 (compile)
[2024-08-14T16:57:41.810Z] 	Could not transfer artifact org.bouncycastle:bcprov-jdk18on:jar:1.78.1 from/to azure-internal (http://artifact-caching-proxy.privatelink.azurecr.io:8080/): Connection reset
[2024-08-14T16:57:41.810Z] 
[2024-08-14T16:57:41.810Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:191)
[2024-08-14T16:57:41.810Z]     at org.jenkinsci.maven.plugins.hpi.TestDependencyMojo.resolveDependencies (TestDependencyMojo.java:777)
[2024-08-14T16:57:41.810Z]     at org.jenkinsci.maven.plugins.hpi.TestDependencyMojo.execute (TestDependencyMojo.java:245)
[2024-08-14T16:57:41.810Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
[2024-08-14T16:57:41.810Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
[2024-08-14T16:57:41.810Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
[2024-08-14T16:57:41.811Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
[2024-08-14T16:57:41.811Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
[2024-08-14T16:57:41.811Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
[2024-08-14T16:57:41.811Z]     at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:903)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:280)
[2024-08-14T16:57:41.812Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:203)
[2024-08-14T16:57:41.812Z]     at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:103)
[2024-08-14T16:57:41.812Z]     at java.lang.reflect.Method.invoke (Method.java:580)
[2024-08-14T16:57:41.813Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
[2024-08-14T16:57:41.813Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
[2024-08-14T16:57:41.813Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
[2024-08-14T16:57:41.813Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[2024-08-14T16:57:41.813Z] [ERROR] 
[2024-08-14T16:57:41.813Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[2024-08-14T16:57:41.813Z] [ERROR] 
[2024-08-14T16:57:41.813Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[2024-08-14T16:57:41.813Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[2024-08-14T16:57:41.914Z] org.jenkins.tools.test.exception.PomExecutionException: mvn -B -V -e -ntp -pl :pipeline-graph-analysis -Dmaven.test.failure.ignore=true -Dsurefire.rerunFailingTestsCount=1 -DforkCount=.75C -Dsurefire.excludesFile=/home/jenkins/agent/workspace/Tools_bom_PR-3190/excludes.txt -DoverrideWar=/home/jenkins/agent/workspace/Tools_bom_PR-3190/target/megawar-weekly.war -Djenkins.version=2.472 -DuseUpperBounds=true hpi:resolve-test-dependencies hpi:test-hpl hpi:test-runtime surefire:test -Djenkins-test-harness.version=2244.v77428109fd1f -DupperBoundsExcludes=org.junit.jupiter:junit-jupiter-api in /home/jenkins/agent/workspace/Tools_bom_PR-3190/target/pct-work/pipeline-graph-analysis-plugin failed with exit status 1
[2024-08-14T16:57:41.914Z] 	at org.jenkins.tools.test.maven.ExternalMavenRunner.run(ExternalMavenRunner.java:110)
[2024-08-14T16:57:41.914Z] 	at org.jenkins.tools.test.PluginCompatTester.testPluginAgainst(PluginCompatTester.java:279)
[2024-08-14T16:57:41.914Z] 	at org.jenkins.tools.test.PluginCompatTester.testPlugins(PluginCompatTester.java:165)
[2024-08-14T16:57:41.914Z] 	at org.jenkins.tools.test.PluginCompatTesterCli.call(PluginCompatTesterCli.java:201)
[2024-08-14T16:57:41.914Z] 	at org.jenkins.tools.test.PluginCompatTesterCli.call(PluginCompatTesterCli.java:44)
[2024-08-14T16:57:41.914Z] 	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
[2024-08-14T16:57:41.914Z] 	at picocli.CommandLine.access$1500(CommandLine.java:148)
[2024-08-14T16:57:41.914Z] 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
[2024-08-14T16:57:41.914Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
[2024-08-14T16:57:41.915Z] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
[2024-08-14T16:57:41.915Z] 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
[2024-08-14T16:57:41.915Z] 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
[2024-08-14T16:57:41.915Z] 	at picocli.CommandLine.execute(CommandLine.java:2174)
[2024-08-14T16:57:41.915Z] 	at org.jenkins.tools.test.CLI.main(CLI.java:13)
```

### Reproduction steps

Run a BOM build with the `full-test` label. It failed for me on Monday with similar errors, but with a different set of plugins.

**Comment by dduportal** [comment]
Started to check the logs and metrics:

- There are no error logs raised by Nginx (in ACP): it means no explicit server-side errors
- The pods (e.g. process) metrics shows a visible usage peak in the time window of this build:
  
  <img width="1725" alt="Capture d’écran 2024-08-14 à 20 58 06" src="https://github.com/user-attachments/assets/c6db2a16-2c26-44e8-bdbd-f64560721840">

  - Note the CPU usage close to 2: might have been throttled since we set up a limit of 2 cpus (https://github.com/jenkins-infra/kubernetes-management/blob/ffab040cae3ec568b62284a575abddfc6524f9fd/config/artifact-caching-proxy_azure-aks.yaml#L37)
  - The network rate is impressive: it peaked around 550 Mbits/s

- But no network errors detected which leads me to think the HTTP client did closed the connection but not sure why.

The underlying nodes metrics shows an expected amount of TCP opened connection we are under the 150 active TCP sockets: it looks like there is an efficient TCP reuse.

<img width="1720" alt="Capture d’écran 2024-08-14 à 21 05 15" src="https://github.com/user-attachments/assets/1f760f33-31b3-4326-9ce2-b5928abe0e9f">


I wonder if disabling the keepalive in the Maven's http wagon might not help on that matter (and disabling connection pooling): https://cloud.google.com/knowledge/kb/cloud-build-error-downloading-maven-dependencies-000004049 (alos mentioned in https://developercommunity.visualstudio.com/t/maven-project-build-failing-with-connection-reset/357696.

This will have an impact on the CPU usage: I'll increase the upper boundary of ACP instances as the nodes CPUs where ACP instances runs still have plenty CPU available:

<img width="871" alt="Capture d’écran 2024-08-14 à 21 11 13" src="https://github.com/user-attachments/assets/34faad22-91ee-4c6c-ad11-cdbdd4959db6">

**Comment by dduportal** [comment]
> > But no network errors detected which leads me to think the HTTP client did closed the connection but not sure why
> 
> I wanted to comment briefly on this statement, since I have (many years ago) implemented TCP/IP from scratch. Unlike `ETIMEDOUT`, `ECONNRESET` is a socket error you can see from `read()`, `write()`, and other operations that indicates that the remote peer has sent a TCP segment with the `RST` flag set. This clearly implicates the server, not the client.

Many thanks for the reminder, I mixed up both states (sill had the https://github.com/jenkins-infra/helpdesk/issues/4204 in mind). Let me check again the metrics with this in mind.

Since it's a BOM build (e.g. pod agents), we can remove the Azure LB from the equation.

**Comment by dduportal** [comment]
> Since it's a BOM build (e.g. pod agents), we can remove the Azure LB from the equation.

Never mind: the LB is used because request are sent through the LB (as per the IP resolved by the DNS `artifact-caching-proxy.privatelink.azurecr.io`).

Need to dive into https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-tcp-reset

**Comment by dduportal** [comment]
@basil you should be able to retry: ACP has now access to more resources and the TCP reset has been disabled on the LB. Note we can re-enable the TCP reset and set it to a bigger limit (defaults to 4 min). I would like to see the impact though

**Comment by basil** [comment]
I am running a new build at https://ci.jenkins.io/job/Tools/job/bom/job/master/3012/

**Comment by basil** [comment]
Unfortunately I am still seeing the same "Connection reset" error in https://ci.jenkins.io/job/Tools/job/bom/job/master/3013/pipeline-console/?selected-node=1073 and a handful of other plugins in that run. It is never the same plugins every time; a different set of plugins fail every time, but they always fail with an ACP error, and only on the Azure ACP.

**Comment by basil** [comment]
I ran a third build, which also had failures in a different set of plugins:

https://ci.jenkins.io/job/Tools/job/bom/job/master/3014/

I think it is safe to say that we cannot do a BOM release at this moment in time due to every build failing in one plugin or another.

**Comment by dduportal** [comment]
I've restarted a build (https://ci.jenkins.io/job/Tools/job/bom/job/master/3015/) with a slightly different ACP setup.

The hostname is changed (manual change on ci.jenkins.io) as I want to ensure the Azure LB is not used: I want it removed from the equation in order to look at the right component in my tcpdumps

**Comment by dduportal** [comment]
If it fails, I have a few ideas to decrease the network strain and unblock the BOM builds).

**Comment by dduportal** [comment]
> I've restarted a build (https://ci.jenkins.io/job/Tools/job/bom/job/master/3015/) with a slightly different ACP setup.
> 
> The hostname is changed (manual change on ci.jenkins.io) as I want to ensure the Azure LB is not used: I want it removed from the equation in order to look at the right component in my tcpdumps

Build #3015 only had a test failure on the jacoco plugin stage (ref. https://ci.jenkins.io/job/Tools/job/bom/job/master/3015/testReport/junit/hudson.plugins.jacoco/ExecutionFileLoaderTest/pct_jacoco_plugin_2_452_x___testLoadBundleWithExecFile/).

I cannot find any mention of the `Connection Reset` in the whole build output.

=> That shows the Loadbalancer is the culprit here. This build had direct link from agent pods to the internal vIP (`ClusterIp`)  so no NAT connections.

@basil I'm relaunching one last build to be sure it keeps the same behavior. Can you help me by confirming the test error is unrelated (or if it is how/why as it mentions a `java.io.EOFException` I hope the agent wasn't failing).


=> ci.jenkins.io puppet agent is disabled to keep the manual setting, I'll persist it tomorrow (today is banking holiday for me)
=> we will still need to add ACP + LB keepalive tuning to avoid this RST problem when using ATH (which must use the LB).

**Comment by dduportal** [comment]
Build 3016 was successful. I hope it will ve enough to unblock the bom release. Really sorry for the inconvenience

**Comment by basil** [comment]
Thanks! I can confirm that `jacoco-plugin` is a known flaky test (nothing to do with infrastructure).

**Comment by dduportal** [comment]
- Configuration persisted: https://github.com/jenkins-infra/jenkins-infra/pull/3608
- Quick (successful) sanity check with https://ci.jenkins.io/job/Plugins/job/jenkins-infra-test-plugin/job/master/260/ which  used the internal ACP hostname for the Linux container and the "private LB" for the Windows 21 ACI agent

I'm triggering a complete BOM build before closing the issue: https://ci.jenkins.io/job/Tools/job/bom/job/master/3022/. If it fails due to ACP I'll keep open and diagnose.

**Comment by dduportal** [comment]
>  https://ci.jenkins.io/job/Tools/job/bom/job/master/3022/. 

Was a success. Let's close the issue.

**Comment by basil** [comment]
Thank you very much. This was highly appreciated!
