### ISSUE TITLE
Hosting of CSP compatibility "microsite" repo

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/helpdesk#4907]
### Service(s)

GitHub, jenkins.io

### Summary

https://www.jenkins.io/doc/book/security/csp/ currently links to https://docs.google.com/spreadsheets/d/1uYrNE5a9SHJdqknkqwXh4F4onk6xwYYDsLJ_588rsnE/edit, which is annoying to maintain.

I built https://github.com/daniel-beck/csp-compatibility as a weekend experiment to replace the spreadsheet. The GH repo format would be more amenable to user contributions via PRs etc.

It's currently using GH pages to publish generated output at https://daniel-beck.github.io/csp-compatibility/
I'm open to changing that (e.g., reports.jenkins.io / actual jenkins.io integration, similar to https://www.jenkins.io/doc/developer/publishing/source-code-hosting/). One complication with full integration might be that I don't think we want to clutter up the regular infra-reports repo, so we would probably store the resource files elsewhere?

To get started, it could probably be transferred as is to `@jenkins-infra` and its GH pages linked to from the jenkins.io docs page. Thoughts?

**Comment by timja** [comment]
Looks nice!

It would be good to add the Jenkins io header and footer.

Simple example:
https://github.com/jenkins-infra/docker-issue-redirect/blob/d5ce819a7ee70675a0cd9e4dec4e943e1ec256d6/docker/index.html#L10

https://github.com/jenkins-infra/docker-issue-redirect/blob/d5ce819a7ee70675a0cd9e4dec4e943e1ec256d6/docker/index.html#L23

A bit of CSS for dark mode would be nice too but I can PR that after hosting.

**Comment by lemeurherve** [comment]
@daniel-beck we're proposing you to transfer your repo into @jenkins-infra org, store the current index.html and the generated JSON into https://reports.jenkins.io/csp-compatibility as a first step via a pipeline using https://github.com/jenkins-infra/pipeline-library/blob/master/vars/publishReports.groovy.

They would then be publicily accessible asap without requiring a new jenkins.io subdomain nor depending on GH pages, and allow you to progress at your own rhythm toward a proper integration into https://www.jenkins.io/doc/book/security/csp/ similar to https://www.jenkins.io/doc/developer/publishing/source-code-hosting/

WDYT?

**Comment by lemeurherve** [comment]
@daniel-beck: gentle ping ICYMI 🙂

(cf your recent mailing list thread [Plugin compatibility with Content Security Policy in Jenkins 2.539+](https://groups.google.com/g/jenkinsci-dev/c/Lw094AJm5zw))

**Comment by daniel-beck** [comment]
I saw, thanks. Just a matter of finding the time.

**Comment by dduportal** [comment]
Looks like the proposal is ok for you @daniel-beck:

- New repo (transferred from you to the `jenkins-infra` organization): https://github.com/jenkins-infra/csp-compatibility
- Adding a deployment job in infra.ci:
  - https://github.com/jenkins-infra/kubernetes-management/pull/7422
  - https://github.com/jenkins-infra/csp-compatibility/pull/15/changes

**Comment by dduportal** [comment]
- Initial deployment does not behave as expected: build succeeded in infra.ci but reports.jenkins.io shows a file at his root named `csp-compatibility` with JSON in it
  - Expectation: we should have a subdirectory `csp-compatibility/` with 2 files in it
  - It is caused by a `publishReports()` pipeline library issue which flattens relative path - Same as https://github.com/jenkins-infra/core-taglibs-report-generator/issues/38 but in the "credential" cases (we only detected and fixed this bug in credential-less cases 🤦 )
- Wip in https://github.com/jenkins-infra/pipeline-library/pull/979

**Comment by dduportal** [comment]
- Deployment is now fixed: https://github.com/jenkins-infra/pipeline-library/pull/979
  - Last build (number `5` went well)
- Cleanup in https://github.com/jenkins-infra/csp-compatibility/pull/16

**Comment by daniel-beck** [comment]
> It would be good to add the Jenkins io header and footer.

Good idea, but I consider that beyond the scope of this request. Probably needs some other cleanup too, given https://github.com/jenkins-infra/csp-compatibility?tab=readme-ov-file#development 😉

**Comment by dduportal** [comment]
- Set up https://github.com/orgs/jenkins-infra/teams/core as admin and https://github.com/orgs/jenkins-infra/teams/jenkins-infra-sre-team as maintainer
- Disabled GH actions (uneeded)

**Comment by dduportal** [comment]
- Added branch protection: PR is required, no force push to main

**Comment by daniel-beck** [comment]
FTR https://jenkins-infra.github.io/csp-compatibility/ still exists. I lack repo admin to have a look around to see whether that can be removed.

**Comment by daniel-beck** [comment]
> FTR https://jenkins-infra.github.io/csp-compatibility/ still exists. I lack repo admin to have a look around to see whether that can be removed.

I unpublished pages at https://github.com/jenkins-infra/csp-compatibility/settings/pages, so this is probably gone soon.

Edit: Gone. I consider this issue resolved.
